import { ArrowRight, BadgeCheck, Box, MapPin, MessageCircle, Scissors, Truck } from 'lucide-react';
import { Link } from 'react-router-dom';
import ProductCard from '../components/ProductCard';
import { products, whatsappUrl } from '../lib/data';

export default function Home(){return <>
  <section className="relative min-h-[720px] overflow-hidden bg-emerald-950 text-white lg:min-h-[760px]">
    <img src="/images/showroom-hero.webp" className="absolute inset-0 h-full w-full object-cover object-center" alt="Premium men's fabric showroom"/>
    <div className="absolute inset-0 bg-gradient-to-r from-[#031f17]/95 via-[#052b20]/70 to-transparent"/>
    <div className="relative mx-auto flex min-h-[720px] max-w-[1440px] items-center px-5 py-20 md:px-10 lg:min-h-[760px] lg:px-16">
      <div className="max-w-2xl reveal"><p className="eyebrow">Azam Market · Lahore</p><h1 className="mt-6 font-display text-5xl font-semibold leading-[1.04] md:text-7xl">Premium Gents Fabrics <span className="italic text-gold-400">Wholesale</span> Supplier</h1><p className="mt-7 max-w-lg text-lg leading-8 text-white/70">Quality fabrics from Azam Market Lahore, curated by the thaan for dealers, retailers and boutiques across Pakistan.</p><div className="mt-10 flex flex-wrap gap-3"><Link to="/catalogue" className="btn-primary">View Collection <ArrowRight size={17}/></Link><a href={whatsappUrl('Assalam-o-Alaikum, I would like to view your wholesale collection.')} target="_blank" className="btn-outline"><MessageCircle size={17}/> WhatsApp Wholesale Inquiry</a></div></div>
    </div>
    <div className="absolute bottom-0 right-0 hidden w-[48%] grid-cols-3 border-t border-l border-white/15 bg-black/20 backdrop-blur-md lg:grid">{[['20+','Fabric ranges'],['4–5','Suits per thaan'],['Nationwide','Delivery']].map(([a,b])=><div key={b} className="border-r border-white/15 p-7"><div className="font-display text-2xl text-gold-400">{a}</div><div className="mt-1 text-[10px] uppercase tracking-widest text-white/50">{b}</div></div>)}</div>
  </section>
  <section className="section bg-[#fbf8f2]"><div className="mx-auto max-w-[1320px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow">Trade collection</p><h2 className="mt-4 max-w-xl font-display text-4xl font-semibold leading-tight text-emerald-950 md:text-5xl">Fabrics selected for your customers.</h2></div><Link to="/catalogue" className="flex items-center gap-2 text-sm font-bold text-emerald-900">Explore the full catalogue <ArrowRight size={16}/></Link></div><div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-3">{products.slice(0,3).map(p=><ProductCard key={p.code} product={p}/>)}</div></div></section>
  <section className="bg-cream"><div className="mx-auto grid max-w-[1440px] lg:grid-cols-2"><div className="min-h-[480px] bg-[url('/images/showroom-hero.png')] bg-cover bg-left"/><div className="flex items-center px-7 py-16 md:px-16 lg:px-20"><div><p className="eyebrow">Built for wholesale</p><h2 className="mt-4 font-display text-4xl font-semibold text-emerald-950 md:text-5xl">The thaan is our standard.</h2><p className="mt-6 max-w-xl leading-8 text-black/55">We understand the real rhythm of fabric trade: consistent lots, accurate colour assortments, dependable packing and direct answers before you buy.</p><div className="mt-9 grid gap-5 sm:grid-cols-2">{[[Box,'Thaan-based inventory','Clear packing and suit yield'],[BadgeCheck,'Checked quality','Trade-ready fabric selection'],[Scissors,'Tailor-friendly cuts','Consistent length and finish'],[Truck,'Pakistan delivery','Dispatch for verified dealers']].map(([Icon,t,d])=><div key={String(t)} className="flex gap-3"><Icon className="mt-1 text-gold-500" size={21}/><div><div className="font-bold text-emerald-950">{String(t)}</div><div className="mt-1 text-sm text-black/45">{String(d)}</div></div></div>)}</div></div></div></div></section>
  <section className="section bg-emerald-900 text-white"><div className="mx-auto flex max-w-[1100px] flex-col items-center text-center"><MapPin className="text-gold-400"/><p className="eyebrow mt-5">Wholesale relationships</p><h2 className="mt-4 font-display text-4xl font-semibold md:text-6xl">From Lahore's fabric heart, to your shop.</h2><p className="mt-6 max-w-2xl leading-8 text-white/60">Register your business requirement and our wholesale desk will share suitable ranges, availability and trade prices directly.</p><Link to="/wholesale" className="btn-primary mt-9">Register as a wholesale buyer <ArrowRight size={17}/></Link></div></section>
  </>}
